import telebot

from telebot import types

import datetime
import time

import schedule

from telebot import types


bot = telebot.TeleBot('5240358466:AAFbV8WT1e4Ye-MWR93gvRnMHEWotsOI3Ig')

@bot.message_handler(commands=['start'])
def start(message):
    bot.send_message(message.chat.id, 'Привет!')



@bot.message_handler(commands = ['url'])
def url(message):
    markup = types.InlineKeyboardMarkup()
    btn_my_site= types.InlineKeyboardButton(text='Наш сайт', url='https://habrahabr.ru')
    markup.add(btn_my_site)
    bot.send_message(message.chat.id, "Нажми на кнопку и перейди на наш сайт.", reply_markup = markup)

    markup = types.InlineKeyboardMarkup()
    btn_my_site= types.InlineKeyboardButton(text='Наш сайт', url='https://habrahabr.ru')
    markup.add(btn_my_site)
    bot.send_message(message.chat.id, "Нажми на кнопку и перейди на наш сайт.", reply_markup = markup)    


@bot.message_handler(commands=['Artery'])
def Artery(message):
    markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
    buttonA = types.KeyboardButton('Кошелек')
    buttonB = types.KeyboardButton('Продать ARTR')
    buttonC = types.KeyboardButton('Купить ARTR')
    buttonD = types.KeyboardButton('История')
    buttonE = types.KeyboardButton('Правила')
    buttonF = types.KeyboardButton('Язык:ru')

    markup.row(buttonA, buttonB, buttonC)
    markup.row(buttonD, buttonE, buttonF)

    bot.send_message(message.chat.id, 'It works!', reply_markup=markup)
    
@bot.message_handler(commands=['Calendar'])
def Calendar(message):

    

    markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
    
    markup.row('<', s[i], '>')
    
    if i == 1:
        t = feb
    if i == 2:
        t = mar
    if i == 3:
        t = apr
    if i == 4:
        t = may
    markup.row('пн', 'вт', 'ср', 'чт', 'пт', 'сб', 'вс')
    markup.row(t[0], t[1], t[2], t[3], t[4], t[5], t[6])
    markup.row(t[7], t[8], t[9], t[10], t[11], t[12], t[13])
    markup.row(t[14], t[15], t[16], t[17], t[18], t[19], t[20])
    markup.row(t[21], t[22], t[23], t[24], t[25], t[26], t[27])
    markup.row(t[28], t[29], t[30], t[31], t[32], t[33], t[34])
    markup.row(t[35], t[36], t[37], t[38], t[39], t[40], t[41])

    bot.send_message(message.chat.id, 'Работаем!', reply_markup=markup)



@bot.message_handler(content_types=["text"])
def handle_text(message):
    global i
    # Если юзер прислал 1, выдаем ему случайный факт
    if message.text.strip() == '>' :
       if i < 4:
           i += 1
    # Если юзер прислал 2, выдаем умную мысль
    elif message.text.strip() == '<':
        if i > 1:
            i -= 1
    # Отсылаем юзеру сообщение в его чат
    # bot.send_message(message.chat.id, answer)
    markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
    
    markup.row('<', s[i], '>')
    if i == 1:
        t = feb
    if i == 2:
        t = mar
    if i == 3:
        t = apr
    if i == 4:
        t = may
    markup.row('пн', 'вт', 'ср', 'чт', 'пт', 'сб', 'вс')
    markup.row(t[0], t[1], t[2], t[3], t[4], t[5], t[6])
    markup.row(t[7], t[8], t[9], t[10], t[11], t[12], t[13])
    markup.row(t[14], t[15], t[16], t[17], t[18], t[19], t[20])
    markup.row(t[21], t[22], t[23], t[24], t[25], t[26], t[27])
    markup.row(t[28], t[29], t[30], t[31], t[32], t[33], t[34])
    markup.row(t[35], t[36], t[37], t[38], t[39], t[40], t[41])

    bot.send_message(message.chat.id, 'Работаем!', reply_markup=markup)

s = ['январь 2022', 'февраль 2022', 'март 2022', 'апрель 2022', 'май 2022']
m = ['jan','feb','mar','apr','may','jun','jul','aug','sep','okt','nov','dec']
feb = [' ', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14',
            '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28',' ',' ',
           ' ',' ', ' ',' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']
mar = [' ', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14',
            '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30',
           '31', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']

apr = [' ', ' ', ' ', ' ', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14',
            '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30',
           ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']

may = [' ', ' ', ' ', ' ', ' ', ' ', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14',
            '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30',
           '31', ' ', ' ', ' ', ' ', ' ']

jun = [' ', ' ', ' ', ' ', ' ', ' ', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14',
            '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30',
           '31', ' ', ' ', ' ', ' ', ' ']

i = 1
#Calendar('1')
    
bot.polling()
